#!/bin/bash

# Linux
GOOS=linux GOARCH=amd64 go build -o bin/present8-linux-64

# macOS
GOOS=darwin GOARCH=amd64 go build -o bin/present8-darwin-64

# Windows
GOOS=windows GOARCH=amd64 go build -o bin/present8-windows-64.exe

# Readme
./bin/present8-linux-64 --output index.html README.md
